services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - internal

  backend:
    build:
      context: ../PrimeMotors-backend
    container_name: backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"
    networks:
      - internal
    env_file:
      - ../PrimeMotors-backend/.env

  frontend:
    build:
      context: ../PrimeMotors-FrontEnd
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./certs:/etc/nginx/ssl:ro
    networks:
      - internal

volumes:
  mysql_data:

networks:
  internal:
    driver: bridge
