services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal

  backend:
    build:
      context: ../PrimeMotors-backend
    container_name: backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - ../PrimeMotors-backend/.env
    networks:
      - internal          

  frontend:
    build:
      context: ../PrimeMotors-FrontEnd
    container_name: frontend
    depends_on:
      - backend
    networks:
      - internal        

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - internal

volumes:
  mysql_data:

networks:
  internal:
    driver: bridge